spring:
  profiles:
    active: local
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MariaDB103Dialect

  datasource:
    username: glnt-user
    password: glnt123!@#
    driver-class-name: org.mariadb.jdbc.Driver
    jdbc-url: jdbc:mariadb://test-db.cwvvhmqatlkn.ap-northeast-2.rds.amazonaws.com:3306/glnt_parking?useSSL=false

logging:
  level:
    ROOT: INFO
    io.github.jhipster: INFO
    thesis: INFO


