spring:
  profiles:
    active: local
  jackson:
    serialization:
      write_dates_as_timestamps: false

  datasource:
    hikari:
      connectionTimeout: 30000
      minimumIdle: 5
      maximum-pool-size: 10
      maxLifetime: 1800000
      poolName: HikariCP
      readOnly: false
      connectionTestQuery: SELECT 1
    type: com.zaxxer.hikari.HikariDataSource

server:
  port: 7000

logging:
  config: