spring:
  profiles:
    active: local
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MariaDB103Dialect

  datasource:
    username: glnt-user
    password: glnt123!@#
    driver-class-name: org.mariadb.jdbc.Driver
    jdbc-url: jdbc:mariadb://test-db.cwvvhmqatlkn.ap-northeast-2.rds.amazonaws.com:3306/glnt_parking?useSSL=false
#  datasource:
#    username: root
#    password: Parking1234!@#$
#    driver-class-name: org.mariadb.jdbc.Driver
#    jdbc-url: jdbc:mariadb://192.168.20.204:3306/glnt_parking?useSSL=false&characterEncoding=utf8

server:
  port: 11000

logging:
  path: /Users/lucy/project/glnt/park
  config: classpath:logback-development.xml
  level:
    ROOT: INFO
    io.github.jhipster: INFO
    thesis: INFO

image:
  filepath: /Users/lucy/project/glnt/park

file:
  filepath: /Users/lucy/project/glnt/park/data

tmap:
  send: off
  url: http://127.0.0.1:10000/api/v1/manage/devices/events

gateway:
  url: http://192.168.20.30:9999/v1

glnt:
  url: http://192.168.20.9:9105

adtcaps:
  url: http://192.168.20.9:9105



