spring:
  profiles:
    active: glnt
  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: io.glnt.gpms.common.configs.DbCustomDialect
        format_sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MariaDB103Dialect

  datasource:
    username: glnt-user
    password: glnt123!@#
    driver-class-name: org.mariadb.jdbc.Driver
    jdbc-url: jdbc:mariadb://test-db.cwvvhmqatlkn.ap-northeast-2.rds.amazonaws.com:3306/glnt_parking_stg?useSSL=false

server:
  port: 11000

logging:
  config: classpath:logback-glnt.xml
  level:
    ROOT: WARN
    io.github.jhipster: WARN
    thesis: WARN

image:
  filepath: C://park//save

tmap:
  send: "OFF"
  url: http://127.0.0.1:10000/api/v1/manage/devices/events

gateway:
  url: http://192.168.20.30:9999/v1



